# Generated by Django 3.0.7 on 2023-12-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_usercontacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usercontacts',
            new_name='Usercontact',
        ),
    ]
