# Generated by Django 3.0.7 on 2023-11-22 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
